services:
  config:
    build: ./config-server
    container_name: config
    volumes:
      - ./config-repo:/config-repo
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 10

  discovery:
    build: ./discovery-server
    container_name: discovery
    depends_on:
      - config
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl","-f","http://localhost:8761/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 10

  pricing-db:
    image: mysql:8
    container_name: pricing-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pricingdb
    volumes:
      - pricing-data:/var/lib/mysql

  reservation-db:
    image: mysql:8
    container_name: reservation-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: reservationdb
    volumes:
      - reservation-data:/var/lib/mysql

  pricing:
    build: ./pricing-service
    container_name: pricing
    depends_on:
      config:
        condition: service_healthy
      discovery:
        condition: service_started
      pricing-db:
        condition: service_started
    restart: on-failure
    # Expose no fixed port; service registers with Eureka using a random port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  reservation:
    build: ./reservation-service
    container_name: reservation
    depends_on:
      config:
        condition: service_healthy
      discovery:
        condition: service_started
      reservation-db:
        condition: service_started
      pricing:
        condition: service_started
    restart: on-failure
    # Expose no fixed port; service registers with Eureka using a random port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  pricing-data:
  reservation-data:
