apiVersion: v1
data:
  client-service.properties: |
    server.port=8080
    spring.datasource.url=jdbc:mysql://client-db:3306/clientsdb?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}
    spring.flyway.baseline-on-migrate=true
    spring.jpa.defer-datasource-initialization=true
    logging.level.org.springframework=INFO
    management.endpoints.web.exposure.include=health,info,prometheus
    management.metrics.tags.application=${spring.application.name}
    management.server.port=9090
    management.tracing.sampling.probability=1.0
    management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
  discovery-service.properties: |
    server.port=8761
    spring.application.name=discovery-service
    management.tracing.sampling.probability=1.0
    management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
  gateway-service.properties: |
    server.port=8080

    spring.cloud.gateway.routes[0].id=client-route
    spring.cloud.gateway.routes[0].uri=lb://CLIENT-SERVICE
    spring.cloud.gateway.routes[0].predicates[0]=Path=/api/clients/**
    spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

    spring.cloud.gateway.routes[1].id=pricing-route
    spring.cloud.gateway.routes[1].uri=lb://PRICING-SERVICE
    spring.cloud.gateway.routes[1].predicates[0]=Path=/api/pricing/**
    spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

    spring.cloud.gateway.routes[2].id=reservation-route
    spring.cloud.gateway.routes[2].uri=lb://RESERVATION-SERVICE
    spring.cloud.gateway.routes[2].predicates[0]=Path=/api/reservations/**
    spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

    spring.cloud.gateway.routes[3].id=session-route
    spring.cloud.gateway.routes[3].uri=lb://SESSION-SERVICE
    spring.cloud.gateway.routes[3].predicates[0]=Path=/api/sessions/**
    spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

    # --- NUEVO ---
    spring.cloud.gateway.routes[4].id=tariffs-route
    spring.cloud.gateway.routes[4].uri=lb://PRICING-SERVICE
    spring.cloud.gateway.routes[4].predicates[0]=Path=/api/tariffs/**
    spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1

    eureka.client.service-url.defaultZone=http://discovery:8761/eureka/
    management.endpoints.web.exposure.include=health,info,prometheus,gateway
    management.metrics.tags.application=${spring.application.name}
    management.endpoint.health.show-details=always
    management.server.port=9090
    management.tracing.sampling.probability=1.0
    management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
  pricing-service.properties: |
    server.port=8080
    spring.datasource.url=jdbc:mysql://pricing-db:3306/pricingdb?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}
    spring.flyway.baseline-on-migrate=true
    spring.jpa.defer-datasource-initialization=true
    spring.jpa.open-in-view=false
    logging.level.org.springframework=INFO
    management.endpoints.web.exposure.include=health,info,prometheus
    management.metrics.tags.application=${spring.application.name}
    management.endpoint.health.show-details=always
    management.server.port=9090
    management.tracing.sampling.probability=1.0
    management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
  reservation-service.properties: |
    server.port=8080
    spring.datasource.url=jdbc:mysql://reservation-db:3306/reservationdb?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}
    spring.flyway.baseline-on-migrate=true
    spring.jpa.open-in-view=false
    logging.level.org.springframework=INFO
    management.endpoints.web.exposure.include=health,info,prometheus
    management.metrics.tags.application=${spring.application.name}
    management.endpoint.health.show-details=always
    management.server.port=9090
    management.tracing.sampling.probability=1.0
    management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
  session-service.properties: |
    spring.datasource.url=jdbc:mysql://session-db:3306/sessiondb?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}

    spring.flyway.baseline-on-migrate=true
    spring.jpa.open-in-view=false
    server.port=8080

    spring.application.name=session-service
    eureka.client.service-url.defaultZone=http://discovery:8761/eureka/

    management.server.port=9090
    management.endpoints.web.exposure.include=health,info,prometheus
    management.metrics.tags.application=${spring.application.name}
    management.tracing.sampling.probability=1.0
    management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config-repo
