# ---------- Config-Server ----------
apiVersion: apps/v1
kind: Deployment
metadata: {name: config}
spec:
  selector: {matchLabels: {app: config}}
  template:
    metadata: {labels: {app: config}}
    spec:
      volumes:
      - name: config-repo
        configMap: {name: config-repo}
      containers:
      - name: config-server
        image: config-server:latest
        imagePullPolicy: Never
        ports:
        - {containerPort: 8888}
        - {containerPort: 9090}
        env:
        - {name: SPRING_PROFILES_ACTIVE, value: "native"}
        - {name: SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS, value: "file:/config-repo"}
        volumeMounts:
        - {name: config-repo, mountPath: /config-repo}
        readinessProbe:
          httpGet: {path: /actuator/health, port: 9090}
          initialDelaySeconds: 10
          periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata: {name: config}
spec:
  ports: [{port: 8888}]
  selector: {app: config}
---
# ---------- Eureka ----------
apiVersion: apps/v1
kind: Deployment
metadata: {name: discovery}
spec:
  selector: {matchLabels: {app: discovery}}
  template:
    metadata: {labels: {app: discovery}}
    spec:
      containers:
      - name: discovery
        image: discovery-server:latest
        imagePullPolicy: Never
        ports:
        - {containerPort: 8761}
        - {containerPort: 9090}
        readinessProbe:
          httpGet: {path: /actuator/health, port: 9090}
          initialDelaySeconds: 10
          periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata: {name: discovery}
spec:
  ports: [{port: 8761}]
  selector: {app: discovery}
---
# ---------- API-Gateway ----------
apiVersion: apps/v1
kind: Deployment
metadata: {name: gateway}
spec:
  selector: {matchLabels: {app: gateway}}
  template:
    metadata: {labels: {app: gateway}}
    spec:
      containers:
      - name: gateway
        image: gateway-service:latest
        imagePullPolicy: Never
        envFrom: [{secretRef:{name: db-credentials}}]
        env:
        - {name: SPRING_CONFIG_IMPORT, value: "configserver:http://config:8888"}
        ports:
        - {containerPort: 8080}
        - {containerPort: 9090}
        readinessProbe:
          httpGet: {path: /actuator/health, port: 9090}
          initialDelaySeconds: 10
          periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata: {name: gateway}
spec:
  ports: [{port: 8080}]
  selector: {app: gateway}
