apiVersion: v1
kind: Secret
metadata: {name: mysql-session-secret}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root_pwd
  MYSQL_PASSWORD: kartingpwd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: mysql-session-pvc}
spec:
  accessModes: [ReadWriteOnce]
  resources: {requests: {storage: 1Gi}}
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: session-db}
spec:
  strategy: {type: Recreate}
  selector: {matchLabels: {app: session-db}}
  template:
    metadata: {labels: {app: session-db}}
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.33
        envFrom: [{secretRef: {name: mysql-session-secret}}]
        env:
        - {name: MYSQL_DATABASE, value: sessiondb}
        - {name: MYSQL_USER, value: karting}
        ports: [{containerPort: 3306}]
        volumeMounts: [{name: data, mountPath: /var/lib/mysql}]
      volumes:
      - name: data
        persistentVolumeClaim: {claimName: mysql-session-pvc}
---
apiVersion: v1
kind: Service
metadata: {name: session-db}
spec:
  ports: [{port: 3306}]
  selector: {app: session-db}
