apiVersion: apps/v1
kind: Deployment
metadata: {name: pricing-service}
spec:
  selector: {matchLabels: {app: pricing-service}}
  template:
    metadata: {labels: {app: pricing-service}}
    spec:
      containers:
      - name: pricing
        image: pricing-service:latest
        envFrom: [{secretRef:{name: db-cred}}]
        env:
        - {name: SPRING_CONFIG_IMPORT, value: "configserver:http://config:8888"}
        - {name: SERVER_PORT,          value: "8080"}
        ports:
        - {containerPort: 8080}
        - {containerPort: 9090}
        readinessProbe:
          httpGet: {path: /actuator/health, port: 9090}
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata: {name: pricing-service}
spec:
  ports: [{port: 8080}]
  selector: {app: pricing-service}
