apiVersion: apps/v1
kind: Deployment
metadata: {name: report-service}
spec:
  selector: {matchLabels: {app: report-service}}
  template:
    metadata: {labels: {app: report-service}}
    spec:
      containers:
      - name: report
        image: report-service:latest
        imagePullPolicy: Never
        env:
        - {name: SPRING_CONFIG_IMPORT, value: "configserver:http://config:8888"}
        ports:
        - {containerPort: 8080}
        - {containerPort: 9090}
        readinessProbe:
          httpGet: {path: /actuator/health, port: 9090}
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata: {name: report-service}
spec:
  ports: [{port: 8080}]
  selector: {app: report-service}
