pipeline {
    agent any

    stages {
        stage("Build Frontend") {
            steps {
                checkout scmGit(
                    branches: [[name: '*/main']],
                    extensions: [],
                    userRemoteConfigs: [[
                        url: 'https://github.com/xshift007/karting.git'
                    ]]
                )
                dir("kartingrm-frontend") {
                    bat "npm ci"
                    bat "npm run build"
                }
            }
        }

        stage("Build & Push Docker Image") {
            steps {
              dir("kartingrm-frontend") {
                script {
                  // <-- named arguments obligatorios
                  withDockerRegistry([ 
                    url:      'https://index.docker.io/v1/', 
                    credentialsId: 'docker-credentials' 
                  ]) {
                    bat "docker build -t xsh1ft/kartingrm-frontend:${env.BUILD_NUMBER} ."
                    bat "docker push xsh1ft/kartingrm-frontend:${env.BUILD_NUMBER}"
                    bat "docker tag xsh1ft/kartingrm-frontend:${env.BUILD_NUMBER} xsh1ft/kartingrm-frontend:latest"
                    bat "docker push xsh1ft/kartingrm-frontend:latest"
                  }
                }
              }
            }
            }

    }

    post {
        always {
            cleanWs()
        }
    }
}
