pipeline {
    agent any

    stages {
        stage("Build Frontend") {
            steps {
                checkout scmGit(
                    branches: [[name: '*/main']],
                    extensions: [],
                    userRemoteConfigs: [[
                        url: 'https://github.com/xshift007/karting.git'
                    ]]
                )
                dir("kartingrm-frontend") {
                    if (isUnix()) {
                        sh 'npm ci'
                        sh 'npm run build'
                    } else {
                        bat 'npm ci'
                        bat 'npm run build'
                    }
                }
            }
        }

        stage("Build & Push Docker Image") {
            steps {
              dir("kartingrm-frontend") {
                script {
                  // <-- named arguments obligatorios
                  withDockerRegistry([
                    url:      'https://index.docker.io/v1/',
                    credentialsId: 'docker-credentials'
                  ]) {
                    if (isUnix()) {
                        sh "docker build -t xsh1ft/karting-frontend:${env.BUILD_NUMBER} ."
                        sh "docker push xsh1ft/karting-frontend:${env.BUILD_NUMBER}"
                        sh "docker tag xsh1ft/karting-frontend:${env.BUILD_NUMBER} xsh1ft/karting-frontend:latest"
                        sh "docker push xsh1ft/karting-frontend:latest"
                    } else {
                        bat "docker build -t xsh1ft/karting-frontend:${env.BUILD_NUMBER} ."
                        bat "docker push xsh1ft/karting-frontend:${env.BUILD_NUMBER}"
                        bat "docker tag xsh1ft/karting-frontend:${env.BUILD_NUMBER} xsh1ft/karting-frontend:latest"
                        bat "docker push xsh1ft/karting-frontend:latest"
                    }
                  }
                }
              }
            }
            }

    }

    post {
        always {
            cleanWs()
        }
    }
}
